# Generated by Django 5.0.6 on 2024-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('binomial_name', models.CharField()),
                ('description', models.CharField()),
                ('sunlight', models.CharField()),
                ('sowing_method', models.CharField()),
            ],
        ),
    ]
