# Generated by Django 5.0.6 on 2024-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0002_rename_plant_name_plant_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='atmospheric_humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ph_maximum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ph_minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
